config/routes.rb
CamelHerder::Application.routes.draw do
  resources :flows

  resources :endpoints

  resources :routes

  resources :camel_contexts

  resources :servers

end

app/models/flow.rb
class Flow < ActiveRecord::Base
  
  belongs_to :from_endpoint, :class_name => "Endpoint", :foreign_key => "from"
  belongs_to :to_endpoint, :class_name => "Endpoint", :foreign_key => "to"
  
end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController
  # GET /flows
  # GET /flows.xml
  def index
    @flows = Flow.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @flows }
    end
  end

  # GET /flows/1
  # GET /flows/1.xml
  def show
    @flow = Flow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @flow }
    end
  end

  # GET /flows/new
  # GET /flows/new.xml
  def new
    @flow = Flow.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @flow }
    end
  end

  # GET /flows/1/edit
  def edit
    @flow = Flow.find(params[:id])
  end

  # POST /flows
  # POST /flows.xml
  def create
    @flow = Flow.new(params[:flow])

    respond_to do |format|
      if @flow.save
        format.html { redirect_to(@flow, :notice => 'Flow was successfully created.') }
        format.xml  { render :xml => @flow, :status => :created, :location => @flow }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @flow.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /flows/1
  # PUT /flows/1.xml
  def update
    @flow = Flow.find(params[:id])

    respond_to do |format|
      if @flow.update_attributes(params[:flow])
        format.html { redirect_to(@flow, :notice => 'Flow was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @flow.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /flows/1
  # DELETE /flows/1.xml
  def destroy
    @flow = Flow.find(params[:id])
    @flow.destroy

    respond_to do |format|
      format.html { redirect_to(flows_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/views/flows/_form.html.erb
<%= form_for(@flow) do |f| %>
  <% if @flow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flow.errors.count, "error") %> prohibited this flow from being saved:</h2>

      <ul>
      <% @flow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.text_field :to %>
  </div>
  <div class="field">
    <%= f.label :references %><br />
    <%= f.text_field :references %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flows/edit.html.erb
<h1>Editing flow</h1>

<%= render 'form' %>

<%= link_to 'Show', @flow %> |
<%= link_to 'Back', flows_path %>

app/views/flows/index.html.erb
<h1>Listing flows</h1>

<table>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>References</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flows.each do |flow| %>
  <tr>
    <td><%= flow.from %></td>
    <td><%= flow.to %></td>
    <td><%= flow.references %></td>
    <td><%= link_to 'Show', flow %></td>
    <td><%= link_to 'Edit', edit_flow_path(flow) %></td>
    <td><%= link_to 'Destroy', flow, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Flow', new_flow_path %>

app/views/flows/new.html.erb
<h1>New flow</h1>

<%= render 'form' %>

<%= link_to 'Back', flows_path %>

app/views/flows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From:</b>
  <%= @flow.from %>
</p>

<p>
  <b>To:</b>
  <%= @flow.to %>
</p>

<p>
  <b>References:</b>
  <%= @flow.references %>
</p>


<%= link_to 'Edit', edit_flow_path(@flow) %> |
<%= link_to 'Back', flows_path %>