config/routes.rb
CamelHerder::Application.routes.draw do
  resources :flows

  resources :endpoints

  resources :routes

  resources :camel_contexts

  resources :servers

end

app/models/server.rb
java_import javax.management.remote.JMXConnector
java_import javax.management.remote.JMXConnectorFactory
java_import javax.management.remote.JMXServiceURL
java_import javax.management.JMX
java_import javax.management.ObjectName

class Server < ActiveRecord::Base
  
  has_many :camel_contexts
  after_create :populate_contexts
  
  @@jmx_connections = {} #TODO: this doesn't seem the best way, but it's what I'm doing atm
  #TODO: Keep alive???
  
  def jmx_connection
    if @@jmx_connections[name].nil?
      url=JMXServiceURL.new uri
      map = java.util.HashMap.new
      creds = [username, password].to_java :String if !username.nil? #TODO: Encrypt pass?
      jmxc = JMXConnectorFactory.connect url, {"jmx.remote.credentials" => creds}     
      @@jmx_connections[name] = jmxc.get_mbean_server_connection
    end
    @@jmx_connections[name]
  end
  
  def populate_contexts
    domains = jmx_connection.domains.to_a
    camel_mbeans = jmx_connection.query_names(nil, nil).select{|m| m.domain == 'org.apache.camel'}
    camel_mbeans.select{|m| m.to_s =~ /type=context/}.each do |m|
      matchdata=m.to_s.match /org.apache.camel:context=(.*?),type=context,name="(.*?)"/
      context = CamelContext.new(:context_name => matchdata[1], :name => matchdata[2])
      camel_contexts << context
      camel_mbeans.select{|m| m.to_s =~ /org.apache.camel:context=#{Regexp.quote(context.context_name)},type=routes,name="(.*?)"/}.
        each do |m|
          routename=m.to_s.match(/name="(.*?)"/)[1]
#          mbeanProxy = JMX.newMBeanProxy(jmx_connection, m, java.lang.Object.class);
          context.routes << Route.new(:name => routename, :object_name => m.to_s)
      end
    end
  end
  
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  # GET /servers
  # GET /servers.xml
  def index
    @servers = Server.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.xml
  def show
    @server = Server.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.xml
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.xml
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to(@server, :notice => 'Server was successfully created.') }
        format.xml  { render :xml => @server, :status => :created, :location => @server }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.xml
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to(@server, :notice => 'Server was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.xml
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to(servers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :uri %><br />
    <%= f.text_field :uri %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Listing servers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Uri</th>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @servers.each do |server| %>
  <tr>
    <td><%= server.name %></td>
    <td><%= server.uri %></td>
    <td><%= server.username %></td>
    <td><%= server.password %></td>
    <td><%= link_to 'Show', server %></td>
    <td><%= link_to 'Edit', edit_server_path(server) %></td>
    <td><%= link_to 'Destroy', server, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @server.name %>
</p>

<p>
  <b>Uri:</b>
  <%= @server.uri %>
</p>

<p>
  <b>Username:</b>
  <%= @server.username %>
</p>

<p>
  <b>Password:</b>
  <%= @server.password %>
</p>


<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>