config/routes.rb
CamelHerder::Application.routes.draw do
  resources :flows

  resources :endpoints

  resources :routes

  resources :camel_contexts

  resources :servers

end

app/models/endpoint.rb
class Endpoint < ActiveRecord::Base
  
  has_many :from_flows, :class_name => "Flow", :foreign_key => "from"
  has_many :to_flows, :class_name => "Flow", :foreign_key => "to"
  
end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  # GET /endpoints
  # GET /endpoints.xml
  def index
    @endpoints = Endpoint.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @endpoints }
    end
  end

  # GET /endpoints/1
  # GET /endpoints/1.xml
  def show
    @endpoint = Endpoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @endpoint }
    end
  end

  # GET /endpoints/new
  # GET /endpoints/new.xml
  def new
    @endpoint = Endpoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @endpoint }
    end
  end

  # GET /endpoints/1/edit
  def edit
    @endpoint = Endpoint.find(params[:id])
  end

  # POST /endpoints
  # POST /endpoints.xml
  def create
    @endpoint = Endpoint.new(params[:endpoint])

    respond_to do |format|
      if @endpoint.save
        format.html { redirect_to(@endpoint, :notice => 'Endpoint was successfully created.') }
        format.xml  { render :xml => @endpoint, :status => :created, :location => @endpoint }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @endpoint.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /endpoints/1
  # PUT /endpoints/1.xml
  def update
    @endpoint = Endpoint.find(params[:id])

    respond_to do |format|
      if @endpoint.update_attributes(params[:endpoint])
        format.html { redirect_to(@endpoint, :notice => 'Endpoint was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @endpoint.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /endpoints/1
  # DELETE /endpoints/1.xml
  def destroy
    @endpoint = Endpoint.find(params[:id])
    @endpoint.destroy

    respond_to do |format|
      format.html { redirect_to(endpoints_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/endpoints_helper.rb
module EndpointsHelper
end

app/views/endpoints/_form.html.erb
<%= form_for(@endpoint) do |f| %>
  <% if @endpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@endpoint.errors.count, "error") %> prohibited this endpoint from being saved:</h2>

      <ul>
      <% @endpoint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uri %><br />
    <%= f.text_field :uri %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/endpoints/edit.html.erb
<h1>Editing endpoint</h1>

<%= render 'form' %>

<%= link_to 'Show', @endpoint %> |
<%= link_to 'Back', endpoints_path %>

app/views/endpoints/index.html.erb
<h1>Listing endpoints</h1>

<table>
  <tr>
    <th>Uri</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @endpoints.each do |endpoint| %>
  <tr>
    <td><%= endpoint.uri %></td>
    <td><%= link_to 'Show', endpoint %></td>
    <td><%= link_to 'Edit', edit_endpoint_path(endpoint) %></td>
    <td><%= link_to 'Destroy', endpoint, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Endpoint', new_endpoint_path %>

app/views/endpoints/new.html.erb
<h1>New endpoint</h1>

<%= render 'form' %>

<%= link_to 'Back', endpoints_path %>

app/views/endpoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uri:</b>
  <%= @endpoint.uri %>
</p>


<%= link_to 'Edit', edit_endpoint_path(@endpoint) %> |
<%= link_to 'Back', endpoints_path %>