config/routes.rb
CamelHerder::Application.routes.draw do
  resources :flows

  resources :endpoints

  resources :routes

  resources :camel_contexts

  resources :servers

end

app/models/route.rb
class Route < ActiveRecord::Base  
    include MBean
  has_many :flows
  belongs_to :camel_context 
  has_one :server, :through => :camel_context
  after_create :update_xml #TODO: Needs to be in canonically better place.
  
  def update_xml
    self.xml= dumpRouteAsXml
    self.save
  end
 # def set_jmx_connection
  
  #, :xml => mbeanProxy.send("dumpRouteAsXml")
  
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  # GET /routes
  # GET /routes.xml
  def index
    @routes = Route.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @routes }
    end
  end

  # GET /routes/1
  # GET /routes/1.xml
  def show
    @route = Route.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @route }
    end
  end

  # GET /routes/new
  # GET /routes/new.xml
  def new
    @route = Route.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @route }
    end
  end

  # GET /routes/1/edit
  def edit
    @route = Route.find(params[:id])
  end

  # POST /routes
  # POST /routes.xml
  def create
    @route = Route.new(params[:route])

    respond_to do |format|
      if @route.save
        format.html { redirect_to(@route, :notice => 'Route was successfully created.') }
        format.xml  { render :xml => @route, :status => :created, :location => @route }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @route.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /routes/1
  # PUT /routes/1.xml
  def update
    @route = Route.find(params[:id])

    respond_to do |format|
      if @route.update_attributes(params[:route])
        format.html { redirect_to(@route, :notice => 'Route was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @route.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.xml
  def destroy
    @route = Route.find(params[:id])
    @route.destroy

    respond_to do |format|
      format.html { redirect_to(routes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :xml %><br />
    <%= f.text_area :xml %>
  </div>
  <div class="field">
    <%= f.label :references %><br />
    <%= f.text_field :references %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<h1>Listing routes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Xml</th>
    <th>References</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @routes.each do |route| %>
  <tr>
    <td><%= route.name %></td>
    <td><%= route.xml %></td>
    <td><%= route.references %></td>
    <td><%= link_to 'Show', route %></td>
    <td><%= link_to 'Edit', edit_route_path(route) %></td>
    <td><%= link_to 'Destroy', route, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @route.name %>
</p>

<p>
  <b>Xml:</b>
  <%= @route.xml %>
</p>

<p>
  <b>References:</b>
  <%= @route.references %>
</p>


<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>